server.port: 9966
spring.profiles: default
server.servlet.contextPath: /api
demo.security.jwt:
  tokenExpirationTime: 15
  refreshTokenExpTime: 60
  tokenIssuer: rishabhfdsasfdasdfs
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
  
spring.devtools.restart.exclude: static/**,public/**
#management.endpoints.web.exposure.include: *

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Rishabh410
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.hbm2ddl.auto: create-update
logging:
  file: d:\logs\application-debug.log
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR